---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-apigee-user
  tags:
  - user

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-os-limits
#  - { role: apigee-fetch-files, fetch_files: '{{ system_config_files }}', fetched_files_dir: '{{ fetched_configs_dir }}' }
  tags:
  - os-tuning

- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - apigee-opdk-setup-openjdk
  tags:
  - openjdk

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-bootstrap
  tags:
  - bootstrap

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-silent-installation-config
  - apigee-opdk-setup-component-installer
#  - { role: apigee-fetch-files, fetch_files: '{{ apigee_config_files }}', fetched_files_dir: '{{ fetched_configs_dir }}' }
  tags:
  - installer

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - { role: apigee-opdk-set-reachable, reachable: false }
  - { role: apigee-opdk-setup-component, profile: '{{ component_profile }}' }
  - { role: apigee-opdk-set-reachable, reachable: true }
#  - { role: apigee-fetch-files, fetch_files: '{{ apigee_log_files }}', fetched_files_dir: '{{ fetched_logs_dir }}' }
  tags:
  - component
