---
- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - { role: apigee-opdk-setup-provisioning, provisioning_action: 'enable-monetization', provisioning_config_file: '{{ opdk_installation_config_file }}'}
