---
- include: configuration/update_cache.yml

- include: configuration/load-opdk-credentials.yml
  vars:
    hosts: 'planet'
  tags:
  - credentials

- hosts: planet
  roles:
  - apigee-opdk-start-components

- hosts: pgmaster[0]

  roles:
  - apigee-opdk-setup-default-settings

  tasks:
  - name: Configure new standby node
    template:
      src: resources/postgresql.properties.j2
      dest: '{{ apigee_installation_home }}/customer/application/postgresql.properties'

  - name: Restarting pgmaster to begin replicating to the extra standby
    shell: '{{ apigee_service }} apigee-postgresql restart'

  - name: Verify that pg_hba.conf reflects both standby servers
    shell: 'cat {{ apigee_installation_home }}/apigee-postgresql/conf/pg_hba.conf'

  - name: Pause and view pg_hba.conf rendered above
    pause:



