---
- hosts: rmp
  serial: 1
  roles:
  - opdk-setup-default-settings
  tasks:
  - name: Obtain router server self report
    ignore_errors: yes
    opdk_server_self:
      server_type: 'router'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
  - debug: var="edge_router_self"

  - name: Obtain message processor server self report
    ignore_errors: yes
    opdk_server_self:
      server_type: 'mp'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  - debug: var="edge_mp_self"


- hosts: pg
  serial: 1
  roles:
  - opdk-setup-default-settings
  tasks:
  - name: Obtain postgres server self report
    ignore_errors: yes
    opdk_server_self:
      server_type: 'ps'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  - debug: var="edge_ps_self"


- hosts: qpid
  serial: 1
  roles:
  - opdk-setup-default-settings
  tasks:
  - name: Obtain qpid server self report
    ignore_errors: yes
    opdk_server_self:
      server_type: 'qs'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  - debug: var="edge_qs_self"


- hosts: ms
  serial: 1
  roles:
  - opdk-setup-default-settings
  tasks:
  - name: Obtain management server self report
    ignore_errors: yes
    opdk_server_self:
      server_type: 'ms'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'

  - debug: var="edge_ms_self"

