---
- hosts: '{{ hosts }}'
  become: yes
  gather_facts: no
  strategy: free
  roles:
  - apigee-opdk-setup-os-minimum
  - apigee-opdk-setup-selinux-disable
  - apigee-opdk-shutdown-iptables
  - apigee-opdk-time-sync
  - apigee-opdk-setup-os-common

