---
- hosts: rmp
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-validate
  tags:
  - validate

- hosts: rmp
  serial: 1
  roles:
  - apigee-opdk-setup-validate-cleanup
  tags:
  - validate
  - validate-cleanup
