---
- hosts: planet
  become: true
  strategy: free
  roles:
  - apigee-opdk-aws-setup

- hosts: '{{ hosts }}'
  become: yes
  gather_facts: no
  strategy: free
  pre_tasks:
  - name: Load credentials from file
    include_vars: '~/.apigee/credentials.yml'
  roles:
  - apigee-opdk-setup-os-minimum
  - apigee-opdk-setup-selinux-disable
  - apigee-opdk-shutdown-iptables
  - apigee-opdk-time-sync
  - apigee-opdk-setup-os-common

