---
- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings
  name: opdk-setup-default-settings

- src: https://github.com/carlosfrias/apigee-opdk-setup-bootstrap-create-archive
  name: opdk-setup-bootstrap-create-archive

- src: https://github.com/carlosfrias/apigee-opdk-setup-os-minimum
  name: opdk-setup-os-minimum

- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings
  name: opdk-setup-default-settings

- src: https://github.com/carlosfrias/apigee-opdk-time-sync
  name: opdk-time-sync

- src: https://github.com/carlosfrias/apigee-opdk-setup-os-common
  name: opdk-setup-os-common

- src: https://github.com/carlosfrias/apigee-opdk-setup-apigee-user
  name: opdk-setup-apigee-user

- src: https://github.com/carlosfrias/apigee-opdk-setup-os-limits
  name: opdk-setup-os-limits

- src: https://github.com/carlosfrias/apigee-opdk-setup-selinux-disable
  name: opdk-setup-selinux-disable

- src: https://github.com/carlosfrias/apigee-opdk-setup-openjdk
  name: opdk-setup-openjdk

- src: https://github.com/carlosfrias/apigee-opdk-setup-bootstrap
  name: opdk-setup-bootstrap

- src: https://github.com/carlosfrias/apigee-opdk-setup-silent-installation-config
  name: opdk-setup-silent-installation-config

- src: https://github.com/carlosfrias/apigee-opdk-setup-component-installer
  name: opdk-setup-component-installer

- src: https://github.com/carlosfrias/apigee-opdk-shutdown-iptables
  name: opdk-shutdown-iptables

- src: https://github.com/carlosfrias/apigee-opdk-setup-bootstrap-download-archive
  name: opdk-setup-bootstrap-download-archive
