---
- hosts: '{{ hosts }}'
  become: yes
  gather_facts: no
  strategy: free
  pre_tasks:
  - name: Load credentials from encrypted file
    include_vars: '~/.apigee/credentials.yml'
  roles:
  - opdk-setup-selinux-disable
  - opdk-setup-os-minimum
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-os-common

