---
- include: configuration/opdk-setup-os.yml
  vars:
    hosts: 'planet'

  tasks:
- include: configuration/update-user.yml
  vars:
    hosts: planet
    user: root

- include: components/opdk-install-component.yml
  vars:
    hosts: 'planet'
    component_profile: 'aio'
  tags:
  - aio

- include: configuration/opdk-setup-org-config.yml
  vars:
    hosts: 'planet'

- include: configuration/opdk-setup-org.yml
  vars:
    hosts: 'planet'

- include: validations/opdk-setup-validate.yml

- include: validations/opdk-setup-log-files.yml
  tags:
  - logs

- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-default-settings
  - opdk-setup-apigee-log-files
  tags:
  - logs
