---
- hosts: planet
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Load credentials from encrypted file
    include_vars: '~/.apigee/credentials.yml'
  roles:
  - opdk-setup-os-minimum
  - opdk-enable-swap
#  - opdk-setup-default-settings

  tasks:
#  - name: Enable swap
#    shell: dd if=/dev/zero of=/var/swap bs=1M count=4096; mkswap /var/swap; swapon /var/swap

- include: configuration/update-user.yml
  vars:
    hosts: planet
    user: root

- include: components/opdk-install-component.yml
  vars:
    hosts: 'planet'
    component_profile: 'aio'
  tags:
  - aio

- include: configuration/opdk-setup-org-config.yml
  vars:
    hosts: 'planet'

- include: configuration/opdk-setup-org.yml
  vars:
    hosts: 'planet'

- include: validations/opdk-setup-validate.yml

- include: validations/opdk-setup-log-files.yml
  tags:
  - logs

- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-default-settings
  - opdk-setup-apigee-log-files
  tags:
  - logs
