---
- hosts: planet
  become: yes
  pre_tasks:

  - name: Load credentials from encrypted file
    include_vars: '~/.apigee/credentials.yml'

  tasks:
  - name: install selinux python bindings
    yum:
      name: libselinux-python
      state: present
    when: ansible_bios_version | lower | search('virtualbox')

  - setup:


- include: configuration/update-user.yml
  vars:
    hosts: planet
    user: root
    delay_before_check: 5


- include: components/opdk-install-component.yml
  vars:
    hosts: 'planet'
    component_profile: 'aio'
  tags:
  - aio


- include: configuration/opdk-setup-org-config.yml


- include: configuration/opdk-setup-org.yml


- include: validations/opdk-setup-validate.yml


- include: validations/opdk-setup-log-files.yml
  tags:
  - logs


- hosts: dc-1
  strategy: free
  roles:
  - opdk-setup-apigee-log-files
  tags:
  - logs
