---
- include: configuration/update_cache.yml

- include: configuration/load-opdk-credentials.yml
  vars:
    hosts: planet
  tags:
  - credentials

- hosts: planet
  tasks:
  - name: Update cache with basic node info
    setup:

  - name: Update cache with AWS info, if running on aws
    ec2_facts:
    when: ansible_bios_version is defined and ansible_bios_version | lower | search('amazon')

- include: configuration/opdk-setup-os.yml
  vars:
    hosts: planet
  tags:
  - os

- include: configuration/update-user.yml
  vars:
    hosts: planet
    user: 'root'
  tags:
  - user

- include: components/opdk-install-component.yml
  vars:
    hosts: planet
    component_profile: 'aio'
  tags:
  - aio

- include: configuration/opdk-setup-org-config.yml
  vars:
    hosts: planet
  tags:
  - org-config

- include: configuration/opdk-setup-org.yml
  vars:
    hosts: planet
  tags:
  - org

- include: validations/opdk-setup-validate.yml
  tags:
  - validation

- include: validations/opdk-setup-log-files.yml
  tags:
  - logs
