---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-apigee-user
  tags:
  - apigee-user
  - apigee-pre-req

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-os-limits
#  - { role: apigee-fetch-files, fetch_files: '{{ system_config_files }}', fetched_files_dir: '{{ fetched_configs_dir }}' }
  tags:
  - apigee-pre-req
  - apigee-tuning

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-openjdk
  tags:
  - apigee-pre-req
  - openjdk

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-bootstrap
  tags:
  - apigee-pre-req
  - apigee-bootstrap

- include: ../configuration/update_cache.yml
  tags:
  - apigee-pre-req
  - apigee-installer

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-silent-installation-config
  - apigee-opdk-setup-component-installer
#  - { role: apigee-fetch-files, fetch_files: '{{ apigee_config_files }}', fetched_files_dir: '{{ fetched_configs_dir }}' }
  tags:
  - apigee-pre-req
  - apigee-installer

- hosts: '{{ hosts }}'
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-setup-component, profile: '{{ component_profile }}' }
#  - { role: apigee-fetch-files, fetch_files: '{{ apigee_log_files }}', fetched_files_dir: '{{ fetched_logs_dir }}' }
  tags:
  - apigee-component
