---
- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - opdk-setup-os-postgres
  - opdk-setup-postgres-config
  tags:
  - os-pg
  - os

- include: ../components/opdk-install-component.yml
  vars:
    hosts: '{{ hosts }}'
    component_profile: 'ps'
  tags:
  - pg

- include: 'opdk-setup-postgres-{{ pg_component}}.yml'
  when: pg_component is defined

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - opdk-setup-postgres-master
  tags:
  - pgmaster

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - opdk-setup-default-settings
  tasks:
  - name: Obtain server self report
    opdk_server_self:
      server_type: 'ps'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
    ignore_errors: yes
  tags:
  - pg
  - pgmaster
