---
- hosts: '{{ hosts }}'
  roles:
  - apigee-opdk-setup-os-minimum
  - apigee-opdk-setup-os-common
  tasks:
  - name: Install needed Python libraries
    become: yes
    pip:
      name: '{{ item }}'
      state: present
    with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1

  - name: Download OS package manager configuration script
    become: yes
    get_url:
      url: https://rpm.nodesource.com/setup_6.x
      dest: /tmp/setup_node.sh
      mode: 0700

  - name: Configure OS package manager
    become: yes
    shell: "/tmp/setup_node.sh"

  - name:  Install OS packages
    become: yes
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - nodejs
    - gcc-c++
    - make

  - name: Install edgemicro
    become: yes
    npm:
      name: '{{ item.name }}'
      version: '{{ item.version }}'
      global: yes
      state: present
    with_items:
    - { name: edgemicro, version: '2.2.1' }

  - name: Create edgemicro default configuration
    shell: 'edgemicro init'


# configure with edge
# edgemicro private configure -m http://172.31.23.239:8080 -r http://172.31.22.140:9001 -o opdk -e test -u opdk@apigee.com -p Apigee123! -v default