---
vpc_subnet_id: '{{ secure_vpc_subnet_id }}'
name_prefix: '{{ secure_name_prefix }}'
env_name: '{{ secure_env_name }}'
bag: '{{ secure_bag }}'
department: '{{ secure_department }}'
company_env: '{{ secure_company_env }}'
owner_contact_info: '{{ secure_owner_contact_info }}'
team_contact_info: '{{ secure_team_contact_info }}'
env: '{{ name_prefix }}-{{ env_name }}'
volume_type: gp2
volume_size: 30
delete_on_termination: true
device_name: /dev/sda1