---
- hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee/credentials.yml

  pre_tasks:
  - setup:

  - ec2_facts:

  - name: "Load provision profile settings"
    include_vars: "profiles/{{ provision_profile }}.yml"

  - name: "Load operating system"
    include_vars: "os/{{ os_selection }}.yml"

  roles:
  - apigee-opdk-aws-create
