---
- hosts: localhost
  connection: local

  vars_files:
  - ~/.apigee/credentials.yml

  pre_tasks:
  - setup:

  - ec2_facts:

  - name: Validate that provision_profile is provided
    fail:
      msg: Please indicate the provision_profile to use from those available in the profiles folder
    when: provision_profile is not defined

  - name: Validate that os_selection is provided
    fail:
      msg: Please indicate the os_selection to use from those available in the os folder
    when: os_selection is not defined

  - name: Validate that security_group is provided
    fail:
      msg: Please indicate the security_group to use from those available in the security folder
    when: security_group is not defined

  - name: Validate that start is provided
    fail:
      msg: Please indicate the starting node
    when: start is not defined

  - name: Validate that end is provided
    fail:
      msg: Please indicate the starting node
    when: end is not defined

  - name: Validate that security_group is provided
    fail:
      msg: Please indicate the security_group to use from those available in the security folder
    when: security_group is not defined

  - name: "Load provision profile settings"
    include_vars: "profiles/{{ provision_profile }}.yml"

  - name: "Load operating system"
    include_vars: "os/{{ os_selection }}.yml"

  - name: "Load security group settings"
    include_vars: "security/{{ security_group }}.yml"

  roles:
  - apigee-opdk-aws-security-group
  - apigee-opdk-aws-create
