---
- hosts: '{{ hosts }}'
#  strategy: free
  roles:
  - opdk-setup-selinux-disable
  - opdk-shutdown-iptables
  - opdk-time-sync
  - opdk-setup-os-minimum
  - opdk-setup-os-common
  - opdk-setup-apigee-user
  - opdk-setup-os-ds

- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - opdk-setup-openjdk

- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - opdk-setup-bootstrap

- hosts: '{{ hosts }}'
  strategy: free
  roles:
  - opdk-setup-silent-installation-config
  - opdk-setup-component-installer

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - { role: opdk-setup-component, profile: '{{ component_profile }}' }


